<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="7" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="382502" started-at="2019-12-05T09:13:34Z" finished-at="2019-12-05T09:19:56Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="382502" started-at="2019-12-05T09:13:34Z" finished-at="2019-12-05T09:19:56Z">
      <class name="com.training.sanity.tests.AssignmentComplexTest">
        <test-method status="PASS" signature="setUpBeforeClass()[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec]" name="setUpBeforeClass" is-config="true" duration-ms="15" started-at="2019-12-05T09:13:34Z" finished-at="2019-12-05T09:13:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeClass -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec]" name="setUp" is-config="true" duration-ms="32724" started-at="2019-12-05T09:13:34Z" finished-at="2019-12-05T09:14:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="Scenario1()[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec]" name="Scenario1" duration-ms="82449" started-at="2019-12-05T09:14:06Z" finished-at="2019-12-05T09:15:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Scenario1 -->
        <test-method status="PASS" signature="TestStatus(org.testng.ITestResult)[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec]" name="TestStatus" is-config="true" duration-ms="1956" started-at="2019-12-05T09:15:29Z" finished-at="2019-12-05T09:15:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Scenario1 status=SUCCESS method=AssignmentComplexTest.Scenario1()[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestStatus -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec]" name="setUp" is-config="true" duration-ms="32948" started-at="2019-12-05T09:15:31Z" finished-at="2019-12-05T09:16:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="Scenario2(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec]" name="Scenario2" duration-ms="14372" started-at="2019-12-05T09:16:04Z" data-provider="xls-inputs" finished-at="2019-12-05T09:16:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[manzoor mehadi]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[manzoor]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[apartments]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[looking for an apartments]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Assertion has Failed and hence the Test Case expected [Thanks You for your message. It has been sent] but found [One or more fields have an error. Please check and try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Assertion has Failed and hence the Test Case expected [Thanks You for your message. It has been sent] but found [One or more fields have an error. Please check and try again.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.training.generics.GenericMethods.AssertText(GenericMethods.java:98)
at com.training.sanity.tests.AssignmentComplexTest.Scenario2(AssignmentComplexTest.java:277)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Scenario2 -->
        <test-method status="PASS" signature="TestStatus(org.testng.ITestResult)[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec]" name="TestStatus" is-config="true" duration-ms="4899" started-at="2019-12-05T09:16:19Z" finished-at="2019-12-05T09:16:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Scenario2 status=FAILURE method=AssignmentComplexTest.Scenario2(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestStatus -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec]" name="setUp" is-config="true" duration-ms="30767" started-at="2019-12-05T09:16:24Z" finished-at="2019-12-05T09:16:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="Scenario2(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec]" name="Scenario2" duration-ms="15866" started-at="2019-12-05T09:16:54Z" data-provider="xls-inputs" finished-at="2019-12-05T09:17:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[alex hales]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[alex@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Plots]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[looking for an plots]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Assertion has Failed and hence the Test Case expected [Thanks You for your message. It has been sent] but found [There was an error trying to send your message. Please try again later.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Assertion has Failed and hence the Test Case expected [Thanks You for your message. It has been sent] but found [There was an error trying to send your message. Please try again later.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.training.generics.GenericMethods.AssertText(GenericMethods.java:98)
at com.training.sanity.tests.AssignmentComplexTest.Scenario2(AssignmentComplexTest.java:277)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Scenario2 -->
        <test-method status="PASS" signature="TestStatus(org.testng.ITestResult)[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec]" name="TestStatus" is-config="true" duration-ms="4484" started-at="2019-12-05T09:17:10Z" finished-at="2019-12-05T09:17:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Scenario2 status=FAILURE method=AssignmentComplexTest.Scenario2(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestStatus -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec]" name="setUp" is-config="true" duration-ms="35655" started-at="2019-12-05T09:17:15Z" finished-at="2019-12-05T09:17:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="Scenario2(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec]" name="Scenario2" duration-ms="6558" started-at="2019-12-05T09:17:50Z" data-provider="xls-inputs" finished-at="2019-12-05T09:17:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mariya]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mariya@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Vilas]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[looking for an vila]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Assertion has Failed and hence the Test Case expected [Thanks You for your message. It has been sent] but found [There was an error trying to send your message. Please try again later.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Assertion has Failed and hence the Test Case expected [Thanks You for your message. It has been sent] but found [There was an error trying to send your message. Please try again later.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.training.generics.GenericMethods.AssertText(GenericMethods.java:98)
at com.training.sanity.tests.AssignmentComplexTest.Scenario2(AssignmentComplexTest.java:277)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Scenario2 -->
        <test-method status="PASS" signature="TestStatus(org.testng.ITestResult)[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec]" name="TestStatus" is-config="true" duration-ms="2418" started-at="2019-12-05T09:17:57Z" finished-at="2019-12-05T09:17:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Scenario2 status=FAILURE method=AssignmentComplexTest.Scenario2(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestStatus -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec]" name="setUp" is-config="true" duration-ms="30688" started-at="2019-12-05T09:18:00Z" finished-at="2019-12-05T09:18:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="Scenario3(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec]" name="Scenario3" duration-ms="6847" started-at="2019-12-05T09:18:30Z" data-provider="xls-inputs" finished-at="2019-12-05T09:18:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[manzoor mehadi]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[manzoor]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[apartments]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[looking for an apartments]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Assertion has Failed and hence the Test Case expected [There was an error trying to send your message. Please try again later.] but found [One or more fields have an error. Please check and try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Assertion has Failed and hence the Test Case expected [There was an error trying to send your message. Please try again later.] but found [One or more fields have an error. Please check and try again.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.training.generics.GenericMethods.AssertText(GenericMethods.java:98)
at com.training.sanity.tests.AssignmentComplexTest.Scenario3(AssignmentComplexTest.java:327)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Scenario3 -->
        <test-method status="PASS" signature="TestStatus(org.testng.ITestResult)[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec]" name="TestStatus" is-config="true" duration-ms="2370" started-at="2019-12-05T09:18:37Z" finished-at="2019-12-05T09:18:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Scenario3 status=FAILURE method=AssignmentComplexTest.Scenario3(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestStatus -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec]" name="setUp" is-config="true" duration-ms="30217" started-at="2019-12-05T09:18:39Z" finished-at="2019-12-05T09:19:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="Scenario3(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec]" name="Scenario3" duration-ms="6775" started-at="2019-12-05T09:19:10Z" data-provider="xls-inputs" finished-at="2019-12-05T09:19:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[alex hales]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[alex@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Plots]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[looking for an plots]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Scenario3 -->
        <test-method status="PASS" signature="TestStatus(org.testng.ITestResult)[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec]" name="TestStatus" is-config="true" duration-ms="1864" started-at="2019-12-05T09:19:16Z" finished-at="2019-12-05T09:19:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Scenario3 status=SUCCESS method=AssignmentComplexTest.Scenario3(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestStatus -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec]" name="setUp" is-config="true" duration-ms="28777" started-at="2019-12-05T09:19:18Z" finished-at="2019-12-05T09:19:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="Scenario3(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec]" name="Scenario3" duration-ms="6980" started-at="2019-12-05T09:19:47Z" data-provider="xls-inputs" finished-at="2019-12-05T09:19:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mariya]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mariya@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Vilas]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[looking for an vila]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Scenario3 -->
        <test-method status="PASS" signature="TestStatus(org.testng.ITestResult)[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec]" name="TestStatus" is-config="true" duration-ms="1918" started-at="2019-12-05T09:19:54Z" finished-at="2019-12-05T09:19:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Scenario3 status=SUCCESS method=AssignmentComplexTest.Scenario3(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.training.sanity.tests.AssignmentComplexTest@66a3ffec] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestStatus -->
      </class> <!-- com.training.sanity.tests.AssignmentComplexTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
