<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="121640" started-at="2019-11-25T10:51:06Z" finished-at="2019-11-25T10:53:07Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="121640" started-at="2019-11-25T10:51:06Z" finished-at="2019-11-25T10:53:07Z">
      <class name="com.training.sanity.tests.AssignmentTest">
        <test-method status="PASS" signature="setUpBeforeClass()[pri:0, instance:com.training.sanity.tests.AssignmentTest@3e6fa38a]" name="setUpBeforeClass" is-config="true" duration-ms="20" started-at="2019-11-25T10:51:06Z" finished-at="2019-11-25T10:51:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeClass -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.training.sanity.tests.AssignmentTest@3e6fa38a]" name="setUp" is-config="true" duration-ms="30635" started-at="2019-11-25T10:51:06Z" finished-at="2019-11-25T10:51:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="Scenario1()[pri:0, instance:com.training.sanity.tests.AssignmentTest@3e6fa38a]" name="Scenario1" duration-ms="10919" started-at="2019-11-25T10:51:36Z" finished-at="2019-11-25T10:51:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Assertion has Failed and hence the Test Case expected [Thanks You for your message. It has been sent] but found [There was an error trying to send your message. Please try again later.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Assertion has Failed and hence the Test Case expected [Thanks You for your message. It has been sent] but found [There was an error trying to send your message. Please try again later.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.training.generics.GenericMethods.AssertText(GenericMethods.java:103)
at com.training.sanity.tests.AssignmentTest.Scenario1(AssignmentTest.java:109)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Scenario1 -->
        <test-method status="PASS" signature="TestStatus(org.testng.ITestResult)[pri:0, instance:com.training.sanity.tests.AssignmentTest@3e6fa38a]" name="TestStatus" is-config="true" duration-ms="2245" started-at="2019-11-25T10:51:47Z" finished-at="2019-11-25T10:51:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Scenario1 status=FAILURE method=AssignmentTest.Scenario1()[pri:0, instance:com.training.sanity.tests.AssignmentTest@3e6fa38a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestStatus -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.training.sanity.tests.AssignmentTest@3e6fa38a]" name="setUp" is-config="true" duration-ms="26557" started-at="2019-11-25T10:51:50Z" finished-at="2019-11-25T10:52:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="Scenario2()[pri:0, instance:com.training.sanity.tests.AssignmentTest@3e6fa38a]" name="Scenario2" duration-ms="6775" started-at="2019-11-25T10:52:16Z" finished-at="2019-11-25T10:52:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Scenario2 -->
        <test-method status="PASS" signature="TestStatus(org.testng.ITestResult)[pri:0, instance:com.training.sanity.tests.AssignmentTest@3e6fa38a]" name="TestStatus" is-config="true" duration-ms="1798" started-at="2019-11-25T10:52:23Z" finished-at="2019-11-25T10:52:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Scenario2 status=SUCCESS method=AssignmentTest.Scenario2()[pri:0, instance:com.training.sanity.tests.AssignmentTest@3e6fa38a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestStatus -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.training.sanity.tests.AssignmentTest@3e6fa38a]" name="setUp" is-config="true" duration-ms="29721" started-at="2019-11-25T10:52:25Z" finished-at="2019-11-25T10:52:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="Scenario3()[pri:0, instance:com.training.sanity.tests.AssignmentTest@3e6fa38a]" name="Scenario3" duration-ms="10752" started-at="2019-11-25T10:52:54Z" finished-at="2019-11-25T10:53:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Assertion has Failed and hence the Test Case expected [Reset Password] but found [WordPress › Error]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Assertion has Failed and hence the Test Case expected [Reset Password] but found [WordPress › Error]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.training.generics.GenericMethods.AssertTitle(GenericMethods.java:96)
at com.training.sanity.tests.AssignmentTest.Scenario3(AssignmentTest.java:176)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Scenario3 -->
        <test-method status="PASS" signature="TestStatus(org.testng.ITestResult)[pri:0, instance:com.training.sanity.tests.AssignmentTest@3e6fa38a]" name="TestStatus" is-config="true" duration-ms="2170" started-at="2019-11-25T10:53:05Z" finished-at="2019-11-25T10:53:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Scenario3 status=FAILURE method=AssignmentTest.Scenario3()[pri:0, instance:com.training.sanity.tests.AssignmentTest@3e6fa38a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestStatus -->
      </class> <!-- com.training.sanity.tests.AssignmentTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
